spring.application.name=screenSoundMusic
spring.datasource.url=jdbc:postgresql://localhost/screenSoundMusic
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true

openai.api.key=${OPENAI_API_KEY}